SportsStore/SportsStore.WebUI/Models/CartIndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using SportsStore.Domain.Entities;

namespace SportsStore.WebUI.Models
{
    public class CartIndexViewModel
    {
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
    }
}

SportsStore/SportsStore.WebUI/Models/PagingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SportsStore.WebUI.Models
{
    public class PagingInfo
    {
        public int TotalItems { get; set; }
        public int ItemsPerPage { get; set; }
        public int CurrentPage { get; set; }
        public int TotalPages
        {
            get { return (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage); }
        }
    }
}

SportsStore/SportsStore.WebUI/Models/ProductListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using SportsStore.Domain.Entities;

namespace SportsStore.WebUI.Models
{
    public class ProductListViewModel
    {
        public IEnumerable<Product> Products { get; set; }
        public PagingInfo PagingInfo { get; set; }
        public string CurrencyCategory { get; set; }
    }
}

SportsStore/SportsStore.WebUI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SportsStore.Domain.Abstract;
using SportsStore.Domain.Entities;
using SportsStore.WebUI.Models;


namespace SportsStore.WebUI.Controllers
{
    public class CartController : Controller
    {
        public IPorductsRepository repository;

        public CartController(IPorductsRepository repo)
        {
            repository = repo;
        }

        //Add Product
        public RedirectToRouteResult AddToCart(Cart cart, int productId, string returnUrl)
        {
            Product product = repository.Products.FirstOrDefault(a => a.ProductID == productId);

            try
            {
                if (product != null)
                {
                    // GetCart().AddItem(product, 1); Added in Infrastructure/Binders
                   if (cart == null) cart = new Cart();
                    cart.AddItem(product, 1);
                }
            }
            catch (Exception exc)
            {
                string s = exc.Message.ToString();
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        //Remove Product
        public RedirectToRouteResult RemoveFromCart(Cart cart, int productId, string returnUrl)
        {
            Product product = repository.Products.FirstOrDefault(b => b.ProductID == productId);

            if (product != null)
            {
                //GetCart().RemoveLine(product);Added in Infrastructure/Binders
                cart.RemoveLine(product);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        /*
         * Replace this logic into Infastrcuture/Binders/ModelBinders.cs
         * 
         * public Cart GetCart()
        {
            Cart cart = (Cart)Session["Cart"];

            if (cart == null)
            {
                cart = new Cart();
                Session["Cart"] = cart;
            }

            return cart;
        }*/

        // Display Cart Summary
        public ViewResult Index(Cart cart, string returnUrl)
        {
            //return View(new CartIndexModel {
            //    Cart = GetCart(),
            //    ReturnUrl = returnUrl
            //} );

            return View(new CartIndexViewModel
            {
                ReturnUrl = returnUrl,
                Cart = cart
            });
        }
    }
}

SportsStore/SportsStore.WebUI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SportsStore.Domain.Abstract;

namespace SportsStore.WebUI.Models
{
    public class NavController : Controller
    {
        private IPorductsRepository repository;

        public NavController(IPorductsRepository repo) {
            repository = repo;
        }
        // GET: Nav
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;
            IEnumerable<string> categories = repository.Products
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return PartialView(categories);
        }
    }
}

SportsStore/SportsStore.WebUI/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SportsStore.Domain.Abstract;
using SportsStore.Domain.Entities;
using SportsStore.WebUI.Models;

namespace SportsStore.WebUI.Controllers
{
    public class ProductController : Controller
    {
        private IPorductsRepository repository;
        public int PageSize = 4;

        public ProductController(IPorductsRepository productRepository) {
            this.repository = productRepository;
        }

        public ViewResult List(string category, int page=1) {
            ProductListViewModel model = new ProductListViewModel {
                   Products = repository.Products
                                .Where(p=>category==null || p.Category==category)
                   .OrderBy(p=>p.ProductID)
                   .Skip((page - 1) * PageSize)
                   .Take(PageSize),
                   PagingInfo = new PagingInfo {
                       CurrentPage = page,
                       ItemsPerPage = PageSize,
                       TotalItems = category==null? repository.Products.Count(): 
                       repository.Products.Where(e=> e.Category==category).Count()
                   },
                   CurrencyCategory = category
            };
            return View(model);
        }
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }
    }
}

SportsStore/SportsStore.WebUI/Views/Cart/Index.cshtml
@model SportsStore.WebUI.Models.CartIndexViewModel

@{
    ViewBag.Title = "Sports Store: Your Cart";
}

<h2>Your Cart</h2>
<table class="table">
    <thead>
        <tr>
            <td>Quantity</td>
            <td>Item</td>
            <td>Price</td>
            <td>Subtotal</td>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Cart.Lines)
        {
            <tr>
                <td>@item.Qunatity</td>
                <td>@item.Product.Name</td>
                <td>@item.Product.Price</td>
                <td>@((item.Qunatity*item.Product.Price).ToString())</td>
                <td>
                    @using (Html.BeginForm("RemoveFromCart", "Cart"))
                    {
                        @Html.Hidden("ProductId", item.Product.ProductID)
                        @Html.HiddenFor(x=>x.ReturnUrl)
                        <input class="btn btn-sm btn-warning" type="submit" value="Remove" />
                    }
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right"> Total:</td>
            <td class="text-left">@Model.Cart.ComputeTotalValue().ToString()</td>
        </tr>
    </tfoot>
</table>
<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Shopping</a>
</div>

SportsStore/SportsStore.WebUI/Views/Nav/Menu.cshtml
@model  IEnumerable<string>

@Html.ActionLink("Home","List","Product",null,
    new { @class="btn btn-block btn-default btn-lg"})

@foreach (var link in Model)
{
    @Html.RouteLink(link, new {
    controller="Product",
    action="List",
    category=link,
    page =1
},new { @class="btn btn-block btn-default btn-lg" + (link==ViewBag.SelectedCategory?" btn-primary":"")})
}

SportsStore/SportsStore.WebUI/Views/Product/List.cshtml
@using SportsStore.WebUI.HtmlHelpers
@model SportsStore.WebUI.Models.ProductListViewModel

@{
    ViewBag.Title = "Products";
}

@foreach (var p in Model.Products)
{
    @Html.Partial("ProductSummary",p)
}
<div class="btn-group pull-right">
    @Html.pageLinks(Model.PagingInfo, x=>Url.Action("List",new { Page = x,category=Model.CurrencyCategory}))
</div>

SportsStore/SportsStore.WebUI/Views/Shared/ProductSummary.cshtml
@model SportsStore.Domain.Entities.Product

<div class="well">
    <h3>
        @Model.Name
    @*<strong> @Model.Description </strong>*@
    <span class="pull-right label label-primary">  @Model.Price.ToString() </span>
</h3>
    @using (Html.BeginForm("AddToCart", "Cart")) {
        <div class="pull-right">
            @Html.HiddenFor(x => x.ProductID)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value="Add to Cart" />
        </div>
    }

    <span class="lead">@Model.Description</span>
</div>

SportsStore/SportsStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
        <div class="navbar navbar-inverse" role="navigation">
            <a class="navbar-brand" href="#">SPORT STORE</a>
        </div>
        <div class="row panel">
            <div id="categories" class="col-xs-3">
              @Html.Action("Menu","Nav")</div>
            <div class="col-xs-8">
                @RenderBody()
            </div>
        </div>
    @*<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>*@

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>